# Generated by Django 2.1.3 on 2018-11-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='place',
            field=models.CharField(default='Seoul', max_length=200, verbose_name='전시장소'),
            preserve_default=False,
        ),
    ]
