# Generated by Django 2.1.3 on 2018-11-16 06:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shows', '0002_show_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='pick_users',
            field=models.ManyToManyField(related_name='pick_shows', related_query_name='pick_show', through='shows.ShowPick', to=settings.AUTH_USER_MODEL),
        ),
    ]
